/**
 * Development Setup Script
 * Run this in Node.js to help setup development environment
 * 
 * Usage: node setup-dev.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function question(query) {
    return new Promise(resolve => rl.question(query, resolve));
}

async function setup() {
    console.log('\n🚀 Bio Link - Development Setup\n');
    console.log('This script will help you configure Supabase for development.\n');

    // Check if config.js already exists
    const configPath = path.join(__dirname, 'config.js');
    if (fs.existsSync(configPath)) {
        const overwrite = await question('config.js already exists. Overwrite? (y/n): ');
        if (overwrite.toLowerCase() !== 'y') {
            console.log('Setup cancelled.');
            rl.close();
            return;
        }
    }

    console.log('\n📋 Supabase Setup Instructions:');
    console.log('1. Go to https://supabase.com and create a new project');
    console.log('2. Go to Settings > API');
    console.log('3. Copy your Project URL and anon public key\n');

    const url = await question('Enter your Supabase Project URL: ');
    const anonKey = await question('Enter your Supabase anon public key: ');

    if (!url || !anonKey || url === 'YOUR_SUPABASE_URL' || anonKey === 'YOUR_SUPABASE_ANON_KEY') {
        console.log('\n❌ Invalid credentials. Setup cancelled.');
        rl.close();
        return;
    }

    // Create config.js
    const configContent = `// Supabase Configuration
// Auto-generated by setup-dev.js
// DO NOT commit this file to git (it's in .gitignore)

const SUPABASE_CONFIG = {
    url: '${url.trim()}',
    anonKey: '${anonKey.trim()}'
};

// Make it available globally for auth-supabase.js
if (typeof window !== 'undefined') {
    window.SUPABASE_CONFIG = SUPABASE_CONFIG;
}

// Export for use in auth-supabase.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = SUPABASE_CONFIG;
}
`;

    fs.writeFileSync(configPath, configContent);
    console.log('\n✅ config.js created successfully!');

    // Check if supabase-setup.sql exists
    const sqlPath = path.join(__dirname, 'supabase-setup.sql');
    if (fs.existsSync(sqlPath)) {
        console.log('\n📝 Next steps:');
        console.log('1. Go to your Supabase project dashboard');
        console.log('2. Navigate to SQL Editor');
        console.log('3. Click "New query"');
        console.log('4. Copy and paste the contents of supabase-setup.sql');
        console.log('5. Click "Run" to execute the SQL script');
        console.log('\n✨ After running the SQL script, your setup is complete!');
    }

    rl.close();
}

setup().catch(err => {
    console.error('Error:', err);
    rl.close();
    process.exit(1);
});

